version: "3.8"

services:
  db:
    image: postgres:15
    container_name: kuna_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MdpDr5F2G4qIYRZWGzo8L5Or88ckyUk2
      POSTGRES_DB: kuna
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optional: expose for local dev, not needed in production

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL} 
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "/api"
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local