version: "3.8"
services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/therapist_matching.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: unless-stopped

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "/api"
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  database_data:
    driver: local